\documentclass[8pt,paper=62mm:100mm,pagesize]{scrartcl}
\usepackage{helvet}
\usepackage[margin=0mm]{geometry}
\usepackage[pdftex]{graphicx}
%\usepackage{pst-barcode}

%\newcommand{\qrcode}{%
%\begin{pspicture}(5mm,5mm)%
%   \psbarcode{http://boel.ch/ln/1234567890123}{eclevel=M}{qrcode}%
%\end{pspicture}}%

\newcommand{\background}{\includegraphics[width=62mm]{./gfx/vinum.png}}
\newcommand{\qr}{\includegraphics[width=18mm]{./qr.png}}

\begin{document}
\sffamily
\setlength{\unitlength}{1mm}
